// <auto-generated />
using System;
using DataSuggesting.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataSuggesting.API.Migrations
{
    [DbContext(typeof(DataSuggestingDbContext))]
    [Migration("20240902152858_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataSuggesting.API.Domain.Entities.DataSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DataSuggestions");
                });

            modelBuilder.Entity("DataSuggesting.API.Domain.Entities.DataSuggestion", b =>
                {
                    b.OwnsOne("DataSuggesting.API.Domain.Entities.Data", "Data", b1 =>
                        {
                            b1.Property<Guid>("DataSuggestionId")
                                .HasColumnType("uuid");

                            b1.HasKey("DataSuggestionId");

                            b1.ToTable("DataSuggestions");

                            b1.WithOwner()
                                .HasForeignKey("DataSuggestionId");

                            b1.OwnsOne("DataSuggesting.API.Domain.Enumerations.Material", "Material", b2 =>
                                {
                                    b2.Property<Guid>("DataSuggestionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text");

                                    b2.HasKey("DataSuggestionId");

                                    b2.ToTable("DataSuggestions");

                                    b2.WithOwner()
                                        .HasForeignKey("DataSuggestionId");
                                });

                            b1.OwnsMany("DataSuggesting.API.Domain.ValueObjects.Coordinate", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("DataSuggestionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("DataSuggestionId", "Id");

                                    b2.ToTable("Coordinate");

                                    b2.WithOwner()
                                        .HasForeignKey("DataSuggestionId");
                                });

                            b1.Navigation("Coordinates");

                            b1.Navigation("Material");
                        });

                    b.OwnsOne("DataSuggesting.API.Domain.ValueObjects.Comment", "Comment", b1 =>
                        {
                            b1.Property<Guid>("DataSuggestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.HasKey("DataSuggestionId");

                            b1.ToTable("DataSuggestions");

                            b1.WithOwner()
                                .HasForeignKey("DataSuggestionId");
                        });

                    b.OwnsOne("DataSuggesting.API.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("DataSuggestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("DataSuggestionId");

                            b1.ToTable("DataSuggestions");

                            b1.WithOwner()
                                .HasForeignKey("DataSuggestionId");
                        });

                    b.Navigation("Comment")
                        .IsRequired();

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
